version: '3'
services:
  modflow_fortran:
    build: .
    container_name: modflow_fortran
    ports:
      - "8081:8081"
    volumes:
      - .:/home/project
    tty: true
    networks:
      static-network:
        ipv4_address: 172.24.0.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.24.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 192.168.0.1/24
